-- Migration: New tables for MealFlow backend modules
-- Run after existing schema (eesara.txt + hasiru.txt)

-- Calculation runs triggered by Subject Clerk
CREATE TABLE IF NOT EXISTS calculations (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    meal VARCHAR(20) NOT NULL CHECK (meal IN ('Breakfast', 'Lunch', 'Dinner')),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'approved', 'sent_to_kitchen')),
    triggered_by INTEGER REFERENCES users(id),
    results JSONB NOT NULL DEFAULT '{}'::jsonb,
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_calc_date_meal UNIQUE (date, meal)
);

-- Orders/Requisitions created from approved calculations
CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    calculation_id INTEGER REFERENCES calculations(id),
    date DATE NOT NULL,
    meal VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'delivered')),
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_cost DECIMAL(12,2) DEFAULT 0,
    notes TEXT,
    created_by INTEGER REFERENCES users(id),
    approved_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Item prices managed by Accountant
CREATE TABLE IF NOT EXISTS item_prices (
    id SERIAL PRIMARY KEY,
    ingredient_id INTEGER NOT NULL,
    price_per_kg DECIMAL(10,2) NOT NULL,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE,
    updated_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_price_ingredient_date UNIQUE (ingredient_id, effective_from)
);

-- Invoices generated by Accountant
CREATE TABLE IF NOT EXISTS invoices (
    id SERIAL PRIMARY KEY,
    order_id INTEGER REFERENCES orders(id),
    invoice_number VARCHAR(50) UNIQUE NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    supplier_name VARCHAR(255) NOT NULL DEFAULT 'Multi Purpose Co-operative Society Ltd, Gampaha',
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax DECIMAL(12,2) NOT NULL DEFAULT 0,
    total DECIMAL(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'paid')),
    payment_date DATE,
    notes TEXT,
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Goods receiving by Kitchen Staff
CREATE TABLE IF NOT EXISTS goods_receiving (
    id SERIAL PRIMARY KEY,
    order_id INTEGER REFERENCES orders(id),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    received_by INTEGER REFERENCES users(id),
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    overall_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (overall_status IN ('pending', 'received', 'issues_found')),
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Issue reports from Kitchen Staff
CREATE TABLE IF NOT EXISTS issue_reports (
    id SERIAL PRIMARY KEY,
    goods_receiving_id INTEGER REFERENCES goods_receiving(id),
    order_id INTEGER REFERENCES orders(id),
    item_name VARCHAR(255) NOT NULL,
    issue_type VARCHAR(50) NOT NULL CHECK (issue_type IN ('spoiled', 'poor_quality', 'partially_damaged', 'quantity_mismatch', 'other')),
    description TEXT,
    photo_urls JSONB DEFAULT '[]'::jsonb,
    severity VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'resolved')),
    reported_by INTEGER REFERENCES users(id),
    acknowledged_by INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    role VARCHAR(30),
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'info',
    is_read BOOLEAN NOT NULL DEFAULT false,
    link VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_calculations_date ON calculations(date);
CREATE INDEX IF NOT EXISTS idx_calculations_status ON calculations(status);
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders(date);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_item_prices_ingredient_id ON item_prices(ingredient_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_date ON invoices(date);
CREATE INDEX IF NOT EXISTS idx_goods_receiving_order_id ON goods_receiving(order_id);
CREATE INDEX IF NOT EXISTS idx_issue_reports_status ON issue_reports(status);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_role ON notifications(role);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
