import { useNavigate } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { MOCK_INVOICES } from "@/lib/module-data";
import { Eye, Download, Printer } from "lucide-react";

const Invoices = () => {
  const navigate = useNavigate();
  return (
    <div className="space-y-6">
      <h1 className="text-heading-md font-bold text-foreground">Invoices</h1>
      <Card>
        <CardContent className="pt-4">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Bill #</TableHead>
                <TableHead>Date</TableHead>
                <TableHead className="hidden md:table-cell">Supplier</TableHead>
                <TableHead className="text-right">Grand Total (Rs)</TableHead>
                <TableHead className="hidden sm:table-cell">Generated By</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {MOCK_INVOICES.map((inv) => (
                <TableRow key={inv.id}>
                  <TableCell className="font-medium">{inv.billNo}</TableCell>
                  <TableCell>{inv.date}</TableCell>
                  <TableCell className="hidden md:table-cell text-muted-foreground max-w-[200px] truncate">{inv.supplier}</TableCell>
                  <TableCell className="text-right font-semibold">Rs. {inv.grandTotal.toLocaleString()}</TableCell>
                  <TableCell className="hidden sm:table-cell">{inv.generatedBy}</TableCell>
                  <TableCell>
                    <div className="flex gap-1">
                      <Button variant="ghost" size="icon" onClick={() => navigate(`/invoices/${inv.id}`)} className="touch-target"><Eye className="h-4 w-4" /></Button>
                      <Button variant="ghost" size="icon" className="touch-target"><Download className="h-4 w-4" /></Button>
                      <Button variant="ghost" size="icon" className="touch-target"><Printer className="h-4 w-4" /></Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
};

export default Invoices;